### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [miragejs/tutorial#4]
Looks like MirageJS [code] and [website] are both under the MIT license; however, this tutorial repository doesn't have a license specified, so it's unclear under what license this code is provided and under what license contributions are accepted.

Could you please clarify that by adding a `LICENSE` file to this repo?

Thanks!

[code]: https://github.com/miragejs/miragejs/blob/master/LICENSE.md
[website]: https://github.com/miragejs/site/blob/master/LICENSE

**Comment by samselikoff** [comment]
Done, thanks!
